name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  new-release:
    name: Release new Version
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4

      - id: setup-java
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - id: build-with-gradle
        name: Build with Gradle
        run: ./gradlew build

      - id: semantic-release
        name: Semantic Release
        if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
        uses: cycjimmy/semantic-release-action@v4

      - id: new-version-check
        name: New version check
        if: (github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')) && steps.semantic-release.outputs.new_release_published == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            core.warning('Changes does not resulted in a new release')
            return "skipped"
          result-encoding: string

      - id: write-summary
        name: Write Step Summary
        if: steps.new-version-check.outputs.result != 'skipped'
        run: "echo 'Images: ${{ steps.docker-meta.outputs.tags }}' >> $GITHUB_STEP_SUMMARY"
